name: "Setup SDL"
description: "Set up SDL"
inputs:
  version:
    description: "Required version of SDL (2.x.y, 2-any, 2-latest, 2-head, 3-head), or git hash"
    default: "2-any"
    required: true
  pre-release:
    description: "Allow pre-releases"
    default: "true"
    required: true
  build-type:
    description: "CMake build type (Release/Debug/RelWithDebInfo/MinSizeRel)"
    default: "Debug"
    required: true
  sdl-test:
    description: "Build and install SDL_test library"
    default: "false"
  cmake-toolchain-file:
    description: "Path of a CMake toolchain file"
  cmake-generator:
    description: "CMake generator name (see https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html)"
  cmake-arguments:
    description: "Extra CMake arguments during configuration"
  install-linux-dependencies:
    description: "Install Linux dependencies"
  shell:
    description: "Run commands as `$shell $file` (with $file containing the build commands)"
  discriminator:
    description: "Unique string to include in the GitHub SDL cache hash"
  add-to-environment:
    description: "Add path of the SDL (shared) library to PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH"
    default: "false"
  token:
    description: "A GitHub API token."
    default: ${{ github.token }}
outputs:
  prefix:
    description: "Actual root of the built SDL package"
  version:
    description: "SDL version"
runs:
  using: "node16"
  main: "packed/index.js"
